# Copyright (C) 2026 Antony Stubbs and contributors

"""Regenerates the protobuf/gRPC stubs from the FROZEN ``proxy.proto``.

Run it with ``make proto``. The output is COMMITTED (``src/parallel_consumer/_generated/``)
so that installing this package needs no ``protoc`` and no proto file - a wheel carries the
stubs, and an sdist install needs no toolchain. ``make proto-check`` regenerates and fails on a
non-empty ``git diff``, which is what keeps the committed copy honest.

Two deliberate choices, both of which a reader will otherwise want to change back:

* **The stubs are generated flat**, from ``proxy.proto`` alone with the schema directory on the
  proto path, rather than under the ``parallelconsumer/proxy/v1/`` tree the proto's package
  implies. The wire is unaffected - the descriptor's ``package`` comes from the ``package``
  statement in the file, not from the output layout - and one flat private module is far easier
  to hide behind this package's own surface than four nested ones.
* **The generated ``import proxy_pb2`` is rewritten to ``from . import proxy_pb2``.**
  ``grpc_tools`` emits a top-level absolute import, which only resolves when the generated
  directory is itself on ``sys.path``; inside a package it raises ``ModuleNotFoundError``. The
  rewrite happens here, as part of generation, so it is never a manual step someone forgets.

The proto is generated with ``grpcio-tools``' own bundled ``protoc`` and matching runtime,
deliberately NOT with the Java build's protoc: the ``.proto`` is the contract, and each
language's generated code need only match its own runtime.
"""

from __future__ import annotations

import os
import pathlib
import re
import subprocess
import sys

MODULE_ROOT = pathlib.Path(__file__).resolve().parent.parent
REPO_ROOT = MODULE_ROOT.parent.parent
SCHEMA_DIR = REPO_ROOT / "parallel-consumer-proxy-protocol" / "src" / "main" / "proto"
PROTO = SCHEMA_DIR / "parallelconsumer" / "proxy" / "v1" / "proxy.proto"
OUT_DIR = MODULE_ROOT / "src" / "parallel_consumer" / "_generated"

GENERATED_NOTICE = (
    "# Generated by tools/generate_proto.py from the frozen proxy.proto - do not edit.\n"
    "# Regenerate with `make proto`; `make proto-check` fails when this copy has drifted.\n"
)


def main() -> int:
    if not PROTO.is_file():
        print(f"schema not found: {PROTO}", file=sys.stderr)
        return 1

    from grpc_tools import protoc  # imported here so --help works without the toolchain

    well_known = os.path.join(os.path.dirname(protoc.__file__), "_proto")
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    status = protoc.main(
        [
            "protoc",
            f"--proto_path={PROTO.parent}",
            f"--proto_path={well_known}",
            f"--python_out={OUT_DIR}",
            f"--pyi_out={OUT_DIR}",
            f"--grpc_python_out={OUT_DIR}",
            str(PROTO),
        ]
    )
    if status != 0:
        return status

    grpc_stub = OUT_DIR / "proxy_pb2_grpc.py"
    rewritten = re.sub(
        r"^import proxy_pb2 as ",
        "from . import proxy_pb2 as ",
        grpc_stub.read_text(encoding="utf-8"),
        flags=re.MULTILINE,
    )
    grpc_stub.write_text(rewritten, encoding="utf-8")

    for generated in sorted(OUT_DIR.glob("proxy_pb2*")):
        text = generated.read_text(encoding="utf-8")
        if not text.startswith(GENERATED_NOTICE):
            generated.write_text(GENERATED_NOTICE + text, encoding="utf-8")

    print(f"generated {', '.join(p.name for p in sorted(OUT_DIR.glob('proxy_pb2*')))}")
    print(f"from {PROTO.relative_to(REPO_ROOT)}")
    return 0


def check() -> int:
    """Regenerates, then fails if the working tree moved - the CI form of `make proto`."""
    status = main()
    if status != 0:
        return status
    diff = subprocess.run(
        ["git", "diff", "--stat", "--", str(OUT_DIR)],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=True,
    )
    if diff.stdout.strip():
        print("generated stubs are stale - run `make proto` and commit the result:")
        print(diff.stdout)
        return 1
    print("generated stubs match the schema")
    return 0


if __name__ == "__main__":
    sys.exit(check() if "--check" in sys.argv[1:] else main())
