# Copyright (C) 2026 Antony Stubbs and contributors

"""Regenerates the protobuf/gRPC stubs for every schema this client speaks.

Run it with ``make proto``. The output is COMMITTED (``src/parallel_consumer/_generated/``)
so that installing this package needs no ``protoc`` and no proto file - a wheel carries the
stubs, and an sdist install needs no toolchain. ``make proto-check`` regenerates and fails on a
non-empty ``git diff``, which is what keeps the committed copy honest.

Two deliberate choices, both of which a reader will otherwise want to change back:

* **The stubs are generated flat**, from ``proxy.proto`` alone with the schema directory on the
  proto path, rather than under the ``parallelconsumer/proxy/v1/`` tree the proto's package
  implies. The wire is unaffected - the descriptor's ``package`` comes from the ``package``
  statement in the file, not from the output layout - and one flat private module is far easier
  to hide behind this package's own surface than four nested ones.
* **The generated ``import proxy_pb2`` is rewritten to ``from . import proxy_pb2``.**
  ``grpc_tools`` emits a top-level absolute import, which only resolves when the generated
  directory is itself on ``sys.path``; inside a package it raises ``ModuleNotFoundError``. The
  rewrite happens here, as part of generation, so it is never a manual step someone forgets.

The proto is generated with ``grpcio-tools``' own bundled ``protoc`` and matching runtime,
deliberately NOT with the Java build's protoc: the ``.proto`` is the contract, and each
language's generated code need only match its own runtime.
"""

from __future__ import annotations

import os
import pathlib
import re
import subprocess
import sys

MODULE_ROOT = pathlib.Path(__file__).resolve().parent.parent
REPO_ROOT = MODULE_ROOT.parent.parent
SCHEMA_DIR = REPO_ROOT / "parallel-consumer-proxy-protocol" / "src" / "main" / "proto"
STREAMS_SCHEMA_DIR = REPO_ROOT / "parallel-consumer-proxy-streams" / "src" / "main" / "proto"
OUT_DIR = MODULE_ROOT / "src" / "parallel_consumer" / "_generated"

#: Every schema this client speaks, and the module stem its stubs get.
#:
#: Two schemas rather than one, and they are deliberately not merged. The first is the frozen wire
#: every client shares. The second is experimental, lives in its own module, and may change or
#: disappear - keeping them separate here is what keeps that difference visible on this side too.
SCHEMAS = (
    (SCHEMA_DIR / "parallelconsumer" / "proxy" / "v1" / "proxy.proto", "proxy"),
    (STREAMS_SCHEMA_DIR / "parallelconsumer" / "streams" / "v1alpha1" / "streams.proto", "streams"),
)

def generated_notice(proto: pathlib.Path) -> str:
    """The header stamped onto each stub, naming the schema it came from.

    Per-schema rather than one shared string: a reader who opens a stub should be able to tell
    which proto it mirrors - and so whether they are looking at the frozen wire or the
    experimental one - without going back to this generator to find out.
    """
    source = proto.relative_to(REPO_ROOT)
    return (
        f"# Generated by tools/generate_proto.py from {source} - do not edit.\n"
        "# Regenerate with `make proto`; `make proto-check` fails when this copy has drifted.\n"
    )


def main() -> int:
    missing = [proto for proto, _ in SCHEMAS if not proto.is_file()]
    if missing:
        for proto in missing:
            print(f"schema not found: {proto}", file=sys.stderr)
        return 1

    from grpc_tools import protoc  # imported here so --help works without the toolchain

    well_known = os.path.join(os.path.dirname(protoc.__file__), "_proto")
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    generated: list[str] = []
    for proto, stem in SCHEMAS:
        status = protoc.main(
            [
                "protoc",
                f"--proto_path={proto.parent}",
                f"--proto_path={well_known}",
                f"--python_out={OUT_DIR}",
                f"--pyi_out={OUT_DIR}",
                f"--grpc_python_out={OUT_DIR}",
                str(proto),
            ]
        )
        if status != 0:
            return status

        grpc_stub = OUT_DIR / f"{stem}_pb2_grpc.py"
        rewritten = re.sub(
            rf"^import {stem}_pb2 as ",
            f"from . import {stem}_pb2 as ",
            grpc_stub.read_text(encoding="utf-8"),
            flags=re.MULTILINE,
        )
        grpc_stub.write_text(rewritten, encoding="utf-8")

        for produced in sorted(OUT_DIR.glob(f"{stem}_pb2*")):
            notice = generated_notice(proto)
            text = produced.read_text(encoding="utf-8")
            if not text.startswith(notice):
                produced.write_text(notice + text, encoding="utf-8")
            generated.append(produced.name)

        print(f"generated {stem}_pb2* from {proto.relative_to(REPO_ROOT)}")

    print(f"{len(generated)} file(s) written to {OUT_DIR.relative_to(REPO_ROOT)}")
    return 0


def check() -> int:
    """Regenerates, then fails if the working tree moved - the CI form of `make proto`."""
    status = main()
    if status != 0:
        return status
    diff = subprocess.run(
        ["git", "diff", "--stat", "--", str(OUT_DIR)],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=True,
    )
    if diff.stdout.strip():
        print("generated stubs are stale - run `make proto` and commit the result:")
        print(diff.stdout)
        return 1
    print("generated stubs match the schema")
    return 0


if __name__ == "__main__":
    sys.exit(check() if "--check" in sys.argv[1:] else main())
