#!/usr/bin/env bash
#
# Copyright (C) 2026 Antony Stubbs and contributors
#

# Offline-protoc parity check for the language-proxy protocol module (astubbs#242).
#
# The module's pom offers -Dproxy.protoc=PATH: instead of downloading protoc at the pinned
# ${protobuf.version} from Maven Central, the build uses whatever protoc it finds on the system
# PATH (the property comment in parallel-consumer-proxy-protocol/pom.xml owns the reasoning).
# That switch must change WHERE protoc comes from and nothing else - not the codegen options,
# not the output directory, not whether the gRPC plugin runs. This script is the durable form
# of the proof the plan's U4 unit did by hand with sha256: it runs codegen once per route and
# FAILS unless the two generated trees are byte-identical.
#
# It needs a protoc binary to stand on the PATH for the offline leg. A real `protoc` already on
# PATH is used as-is; when there is none, the script falls back to the binary the default leg
# just downloaded into the plugin's cache - same version, so exact parity is the only acceptable
# result, and the check runs anywhere the default build runs, with no extra tooling. When the
# PATH protoc is a DIFFERENT version than the pin, a byte difference is expected rather than a
# wiring bug - the failure message says so and names both versions.
#
# Usage (from the repo root, JAVA_HOME set as for bin/build.sh):
#   parallel-consumer-proxy-protocol/src/test/scripts/verify-offline-protoc-parity.sh
#
# Exit codes: 0 = byte-identical, 1 = outputs differ or a build failed, 2 = no protoc obtainable.

set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

MODULE=parallel-consumer-proxy-protocol
GEN_DIR="$MODULE/target/generated-protobuf"
PINNED_VERSION="$(sed -n 's/.*<protobuf.version>\(.*\)<\/protobuf.version>.*/\1/p' "$MODULE/pom.xml")"

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

run_codegen() {
    ./mvnw --batch-mode -q -pl ":$MODULE" -am clean generate-sources "$@"
}

hash_generated_tree() {
    if [[ ! -d "$GEN_DIR" ]]; then
        echo "FAIL: $GEN_DIR does not exist after codegen - the output directory moved?" >&2
        exit 1
    fi
    (cd "$GEN_DIR" && find . -type f | LC_ALL=C sort | xargs -r sha256sum) > "$1"
    if [[ ! -s "$1" ]]; then
        echo "FAIL: $GEN_DIR is empty after codegen" >&2
        exit 1
    fi
}

echo "== leg 1: default route (protoc $PINNED_VERSION downloaded from Maven Central) =="
run_codegen
hash_generated_tree "$WORK/default.sha256"

if command -v protoc > /dev/null 2>&1; then
    path_protoc="$(command -v protoc)"
else
    # No system protoc: promote the binary the default leg just cached. find's pattern must skip
    # the protoc-gen-grpc-java executable that lives beside it.
    cached="$(find "$MODULE/target/protobuf-maven-plugin" -name 'protoc-*.exe' ! -name 'protoc-gen-*' 2> /dev/null | head -n 1)"
    if [[ -z "$cached" ]]; then
        echo "FAIL: no protoc on PATH and no plugin-cached binary to fall back to" >&2
        exit 2
    fi
    mkdir -p "$WORK/pathbin"
    cp "$cached" "$WORK/pathbin/protoc"
    chmod +x "$WORK/pathbin/protoc"
    export PATH="$WORK/pathbin:$PATH"
    path_protoc="$WORK/pathbin/protoc"
fi
path_protoc_version="$("$path_protoc" --version)"
echo "== leg 2: offline route (-Dproxy.protoc=PATH -> $path_protoc, $path_protoc_version) =="
run_codegen -Dproxy.protoc=PATH
hash_generated_tree "$WORK/offline.sha256"

if diff -u "$WORK/default.sha256" "$WORK/offline.sha256"; then
    echo "PASS: default and offline protoc routes generated byte-identical output" \
        "($(wc -l < "$WORK/default.sha256") files, $path_protoc_version)"
else
    echo "FAIL: the -Dproxy.protoc=PATH route generated different bytes than the default route." >&2
    echo "  pinned protobuf.version: $PINNED_VERSION; PATH protoc: $path_protoc_version." >&2
    echo "  If those versions differ, the difference is expected protoc drift, not broken wiring -" >&2
    echo "  but it is exactly why CI and releases must use the default route (see the proxy.protoc" >&2
    echo "  property comment in $MODULE/pom.xml)." >&2
    exit 1
fi
