package io.confluent.parallelconsumer.internal;

/*-
 * Copyright (C) 2020-2022 Confluent, Inc.
 * Modifications Copyright (C) 2026 Antony Stubbs and contributors
 */

import io.confluent.csid.utils.StringUtils;

/**
 * Internal {@link RuntimeException}
 * <p>
 * Constructors are hand-written rather than generated by Lombok's {@code @StandardException}. Mixing that
 * annotation with the hand-written varargs constructor below (which used to delegate via {@code this(...)}
 * to a Lombok-generated constructor) triggered a flaky annotation-processing race: javac intermittently
 * attributed references to the generated constructors before Lombok had produced them in that compile
 * round, so the whole compile of the class - and every {@code new InternalRuntimeException(...)} call site
 * - failed non-deterministically. Writing the constructors by hand removes the annotation-processing
 * dependency entirely, making compilation deterministic. The varargs constructor now calls {@code super(...)}
 * (a JDK {@link RuntimeException} constructor that always exists) instead of {@code this(...)}.
 *
 * @author Antony Stubbs
 * @see InternalException
 */
public class InternalRuntimeException extends RuntimeException {

    public InternalRuntimeException() {
        super();
    }

    public InternalRuntimeException(String message) {
        super(message);
    }

    public InternalRuntimeException(String message, Throwable cause) {
        super(message, cause);
    }

    public InternalRuntimeException(Throwable cause) {
        super(cause);
    }

    /**
     * @see StringUtils#msg(String, Object...)
     */
    public InternalRuntimeException(String message, Throwable cause, Object... args) {
        super(StringUtils.msg(message, args), cause);
    }

    /**
     * @see StringUtils#msg(String, Object...)
     */
    public static InternalRuntimeException msg(String message, Object... vars) {
        return new InternalRuntimeException(StringUtils.msg(message, vars));
    }

}
