package bz.stub.parallelconsumer.internal;

/*-
 * Copyright (C) 2020-2022 Confluent, Inc.
 * Modifications Copyright (C) 2026 Antony Stubbs and contributors
 */

import bz.stub.parallelconsumer.internal.utils.StringUtils;

/**
 * Internal {@link RuntimeException}
 * <p>
 * Named with a {@code PC} prefix, rather than the bare {@code InternalRuntimeException} this class used to
 * carry, because the unprefixed name reads like it could be a JDK type. The prefix says at a glance whose
 * exception this is. This is a deliberate, approved API break, not an incidental rename.
 * <p>
 * Constructors are hand-written rather than generated by Lombok's {@code @StandardException}. Mixing that
 * annotation with the hand-written varargs constructor below (which used to delegate via {@code this(...)}
 * to a Lombok-generated constructor) triggered a flaky annotation-processing race: javac intermittently
 * attributed references to the generated constructors before Lombok had produced them in that compile
 * round, so the whole compile of the class - and every {@code new PCInternalRuntimeException(...)} call site
 * - failed non-deterministically. Writing the constructors by hand removes the annotation-processing
 * dependency entirely, making compilation deterministic. The varargs constructor now calls {@code super(...)}
 * (a JDK {@link RuntimeException} constructor that always exists) instead of {@code this(...)}.
 *
 * @author Antony Stubbs
 * @see InternalException
 */
public class PCInternalRuntimeException extends RuntimeException {

    public PCInternalRuntimeException() {
        super();
    }

    public PCInternalRuntimeException(String message) {
        super(message);
    }

    public PCInternalRuntimeException(String message, Throwable cause) {
        super(message, cause);
    }

    public PCInternalRuntimeException(Throwable cause) {
        super(cause);
    }

    /**
     * @see StringUtils#msg(String, Object...)
     */
    public PCInternalRuntimeException(String message, Throwable cause, Object... args) {
        super(StringUtils.msg(message, args), cause);
    }

    /**
     * @see StringUtils#msg(String, Object...)
     */
    public static PCInternalRuntimeException msg(String message, Object... vars) {
        return new PCInternalRuntimeException(StringUtils.msg(message, vars));
    }

}
