# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: parallelconsumer/proxy/v1/proxy.proto for package 'Bz.Stub.ParallelConsumer.Proxy.V1'
# Original file comments:
# Copyright (C) 2026 Antony Stubbs and contributors
#
# ============================================================================
# FROZEN SCHEMA - THIS IS THE CONTRACT (v1).
#
# Frozen by the language-proxy plan's freeze unit (astubbs#242), on the
# spike's evidence: the provisional schema carried one record end to end
# through both Java transports unchanged, and the message set was then
# completed for the lease/reconnect, terminal-outcome and lifecycle units,
# each message specified by a named unit's scenarios.
#
# After this freeze the wire may only GAIN, never change. A protocol change
# is an event with a cost, not an edit (KTD21):
#   - fields and messages may be ADDED; nothing may be removed, renumbered,
#     retyped or renamed - `buf breaking` in the FILE category enforces this
#     in CI (bin/check-proto-breaking.sh), and FILE is deliberate: WIRE would
#     permit source-breaking changes the compatibility promise (R38) forbids;
#   - every addition ships with a capability entry (see Configure/Configured
#     `capabilities`) so it is negotiated in the handshake, never inferred
#     from field presence;
#   - every addition ships with a note naming which client libraries must be
#     revisited.
#
# The human-readable contract is parallel-consumer-proxy/docs/
# protocol-specification.md - a client author reads that, not the proxy's
# Java. The two are kept in lockstep by a schema-coverage test that fails
# when a message or field here is missing from the specification. A golden
# serialized session (src/test/resources/.../golden-*.bin) pins the wire
# bytes every language's parser must accept.
# ============================================================================
#

require 'grpc'
require 'parallelconsumer/proxy/v1/proxy_pb'

module Bz
  module Stub
    module ParallelConsumer
      module Proxy
        module V1
          module ProxyService
            # The single bidirectional session stream between a client library's admin
            # connection and the sidecar proxy. The first client message must be
            # Configure (fresh session) or Manifest (reconnect within the protection
            # window); the proxy replies Configured either way, and then dispatches
            # records.
            class Service

              include ::GRPC::GenericService

              self.marshal_class_method = :encode
              self.unmarshal_class_method = :decode
              self.service_name = 'parallelconsumer.proxy.v1.ProxyService'

              rpc :Session, stream(::Bz::Stub::ParallelConsumer::Proxy::V1::ClientMessage), stream(::Bz::Stub::ParallelConsumer::Proxy::V1::ProxyMessage)
            end

            Stub = Service.rpc_stub_class
          end
        end
      end
    end
  end
end
