# Generated by tools/generate_proto.py from parallel-consumer-proxy-protocol/src/main/proto/parallelconsumer/proxy/v1/proxy.proto - do not edit.
# Regenerate with `make proto`; `make proto-check` fails when this copy has drifted.
from google.protobuf import duration_pb2 as _duration_pb2
from google.protobuf import timestamp_pb2 as _timestamp_pb2
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from collections.abc import Iterable as _Iterable, Mapping as _Mapping
from typing import ClassVar as _ClassVar, Optional as _Optional, Union as _Union

DESCRIPTOR: _descriptor.FileDescriptor

class ProcessingOrder(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    PROCESSING_ORDER_UNSPECIFIED: _ClassVar[ProcessingOrder]
    PROCESSING_ORDER_UNORDERED: _ClassVar[ProcessingOrder]
    PROCESSING_ORDER_PARTITION: _ClassVar[ProcessingOrder]
    PROCESSING_ORDER_KEY: _ClassVar[ProcessingOrder]

class CommitMode(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    COMMIT_MODE_UNSPECIFIED: _ClassVar[CommitMode]
    COMMIT_MODE_PERIODIC_TRANSACTIONAL_PRODUCER: _ClassVar[CommitMode]
    COMMIT_MODE_PERIODIC_CONSUMER_SYNC: _ClassVar[CommitMode]
    COMMIT_MODE_PERIODIC_CONSUMER_ASYNCHRONOUS: _ClassVar[CommitMode]

class InvalidOffsetMetadataPolicy(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    INVALID_OFFSET_METADATA_POLICY_UNSPECIFIED: _ClassVar[InvalidOffsetMetadataPolicy]
    INVALID_OFFSET_METADATA_POLICY_FAIL: _ClassVar[InvalidOffsetMetadataPolicy]
    INVALID_OFFSET_METADATA_POLICY_IGNORE: _ClassVar[InvalidOffsetMetadataPolicy]
PROCESSING_ORDER_UNSPECIFIED: ProcessingOrder
PROCESSING_ORDER_UNORDERED: ProcessingOrder
PROCESSING_ORDER_PARTITION: ProcessingOrder
PROCESSING_ORDER_KEY: ProcessingOrder
COMMIT_MODE_UNSPECIFIED: CommitMode
COMMIT_MODE_PERIODIC_TRANSACTIONAL_PRODUCER: CommitMode
COMMIT_MODE_PERIODIC_CONSUMER_SYNC: CommitMode
COMMIT_MODE_PERIODIC_CONSUMER_ASYNCHRONOUS: CommitMode
INVALID_OFFSET_METADATA_POLICY_UNSPECIFIED: InvalidOffsetMetadataPolicy
INVALID_OFFSET_METADATA_POLICY_FAIL: InvalidOffsetMetadataPolicy
INVALID_OFFSET_METADATA_POLICY_IGNORE: InvalidOffsetMetadataPolicy

class ClientMessage(_message.Message):
    __slots__ = ("configure", "report", "heartbeat", "manifest", "worker_died")
    CONFIGURE_FIELD_NUMBER: _ClassVar[int]
    REPORT_FIELD_NUMBER: _ClassVar[int]
    HEARTBEAT_FIELD_NUMBER: _ClassVar[int]
    MANIFEST_FIELD_NUMBER: _ClassVar[int]
    WORKER_DIED_FIELD_NUMBER: _ClassVar[int]
    configure: Configure
    report: Report
    heartbeat: Heartbeat
    manifest: Manifest
    worker_died: WorkerDied
    def __init__(self, configure: _Optional[_Union[Configure, _Mapping]] = ..., report: _Optional[_Union[Report, _Mapping]] = ..., heartbeat: _Optional[_Union[Heartbeat, _Mapping]] = ..., manifest: _Optional[_Union[Manifest, _Mapping]] = ..., worker_died: _Optional[_Union[WorkerDied, _Mapping]] = ...) -> None: ...

class ProxyMessage(_message.Message):
    __slots__ = ("configured", "dispatch", "drop", "shutdown", "set_executor_count")
    CONFIGURED_FIELD_NUMBER: _ClassVar[int]
    DISPATCH_FIELD_NUMBER: _ClassVar[int]
    DROP_FIELD_NUMBER: _ClassVar[int]
    SHUTDOWN_FIELD_NUMBER: _ClassVar[int]
    SET_EXECUTOR_COUNT_FIELD_NUMBER: _ClassVar[int]
    configured: Configured
    dispatch: Dispatch
    drop: Drop
    shutdown: Shutdown
    set_executor_count: SetExecutorCount
    def __init__(self, configured: _Optional[_Union[Configured, _Mapping]] = ..., dispatch: _Optional[_Union[Dispatch, _Mapping]] = ..., drop: _Optional[_Union[Drop, _Mapping]] = ..., shutdown: _Optional[_Union[Shutdown, _Mapping]] = ..., set_executor_count: _Optional[_Union[SetExecutorCount, _Mapping]] = ...) -> None: ...

class Configure(_message.Message):
    __slots__ = ("topics", "topic_pattern", "max_concurrency", "kafka_properties", "capabilities", "ordering", "commit_mode", "commit_interval", "default_message_retry_delay", "send_timeout", "offset_commit_timeout", "shutdown_timeout", "drain_timeout", "threshold_for_time_spend_in_queue_warning", "sasl_authentication_retry_timeout", "sasl_authentication_exception_retry_backoff", "max_failure_history", "invalid_offset_metadata_policy", "launch_token", "terminal_topic", "lease_duration", "heartbeat_interval", "reconnect_window", "message_buffer_size", "initial_load_factor", "maximum_load_factor", "pc_instance_tag")
    class KafkaPropertiesEntry(_message.Message):
        __slots__ = ("key", "value")
        KEY_FIELD_NUMBER: _ClassVar[int]
        VALUE_FIELD_NUMBER: _ClassVar[int]
        key: str
        value: str
        def __init__(self, key: _Optional[str] = ..., value: _Optional[str] = ...) -> None: ...
    TOPICS_FIELD_NUMBER: _ClassVar[int]
    TOPIC_PATTERN_FIELD_NUMBER: _ClassVar[int]
    MAX_CONCURRENCY_FIELD_NUMBER: _ClassVar[int]
    KAFKA_PROPERTIES_FIELD_NUMBER: _ClassVar[int]
    CAPABILITIES_FIELD_NUMBER: _ClassVar[int]
    ORDERING_FIELD_NUMBER: _ClassVar[int]
    COMMIT_MODE_FIELD_NUMBER: _ClassVar[int]
    COMMIT_INTERVAL_FIELD_NUMBER: _ClassVar[int]
    DEFAULT_MESSAGE_RETRY_DELAY_FIELD_NUMBER: _ClassVar[int]
    SEND_TIMEOUT_FIELD_NUMBER: _ClassVar[int]
    OFFSET_COMMIT_TIMEOUT_FIELD_NUMBER: _ClassVar[int]
    SHUTDOWN_TIMEOUT_FIELD_NUMBER: _ClassVar[int]
    DRAIN_TIMEOUT_FIELD_NUMBER: _ClassVar[int]
    THRESHOLD_FOR_TIME_SPEND_IN_QUEUE_WARNING_FIELD_NUMBER: _ClassVar[int]
    SASL_AUTHENTICATION_RETRY_TIMEOUT_FIELD_NUMBER: _ClassVar[int]
    SASL_AUTHENTICATION_EXCEPTION_RETRY_BACKOFF_FIELD_NUMBER: _ClassVar[int]
    MAX_FAILURE_HISTORY_FIELD_NUMBER: _ClassVar[int]
    INVALID_OFFSET_METADATA_POLICY_FIELD_NUMBER: _ClassVar[int]
    LAUNCH_TOKEN_FIELD_NUMBER: _ClassVar[int]
    TERMINAL_TOPIC_FIELD_NUMBER: _ClassVar[int]
    LEASE_DURATION_FIELD_NUMBER: _ClassVar[int]
    HEARTBEAT_INTERVAL_FIELD_NUMBER: _ClassVar[int]
    RECONNECT_WINDOW_FIELD_NUMBER: _ClassVar[int]
    MESSAGE_BUFFER_SIZE_FIELD_NUMBER: _ClassVar[int]
    INITIAL_LOAD_FACTOR_FIELD_NUMBER: _ClassVar[int]
    MAXIMUM_LOAD_FACTOR_FIELD_NUMBER: _ClassVar[int]
    PC_INSTANCE_TAG_FIELD_NUMBER: _ClassVar[int]
    topics: _containers.RepeatedScalarFieldContainer[str]
    topic_pattern: str
    max_concurrency: int
    kafka_properties: _containers.ScalarMap[str, str]
    capabilities: _containers.RepeatedScalarFieldContainer[str]
    ordering: ProcessingOrder
    commit_mode: CommitMode
    commit_interval: _duration_pb2.Duration
    default_message_retry_delay: _duration_pb2.Duration
    send_timeout: _duration_pb2.Duration
    offset_commit_timeout: _duration_pb2.Duration
    shutdown_timeout: _duration_pb2.Duration
    drain_timeout: _duration_pb2.Duration
    threshold_for_time_spend_in_queue_warning: _duration_pb2.Duration
    sasl_authentication_retry_timeout: _duration_pb2.Duration
    sasl_authentication_exception_retry_backoff: _duration_pb2.Duration
    max_failure_history: int
    invalid_offset_metadata_policy: InvalidOffsetMetadataPolicy
    launch_token: str
    terminal_topic: str
    lease_duration: _duration_pb2.Duration
    heartbeat_interval: _duration_pb2.Duration
    reconnect_window: _duration_pb2.Duration
    message_buffer_size: int
    initial_load_factor: int
    maximum_load_factor: int
    pc_instance_tag: str
    def __init__(self, topics: _Optional[_Iterable[str]] = ..., topic_pattern: _Optional[str] = ..., max_concurrency: _Optional[int] = ..., kafka_properties: _Optional[_Mapping[str, str]] = ..., capabilities: _Optional[_Iterable[str]] = ..., ordering: _Optional[_Union[ProcessingOrder, str]] = ..., commit_mode: _Optional[_Union[CommitMode, str]] = ..., commit_interval: _Optional[_Union[datetime.timedelta, _duration_pb2.Duration, _Mapping]] = ..., default_message_retry_delay: _Optional[_Union[datetime.timedelta, _duration_pb2.Duration, _Mapping]] = ..., send_timeout: _Optional[_Union[datetime.timedelta, _duration_pb2.Duration, _Mapping]] = ..., offset_commit_timeout: _Optional[_Union[datetime.timedelta, _duration_pb2.Duration, _Mapping]] = ..., shutdown_timeout: _Optional[_Union[datetime.timedelta, _duration_pb2.Duration, _Mapping]] = ..., drain_timeout: _Optional[_Union[datetime.timedelta, _duration_pb2.Duration, _Mapping]] = ..., threshold_for_time_spend_in_queue_warning: _Optional[_Union[datetime.timedelta, _duration_pb2.Duration, _Mapping]] = ..., sasl_authentication_retry_timeout: _Optional[_Union[datetime.timedelta, _duration_pb2.Duration, _Mapping]] = ..., sasl_authentication_exception_retry_backoff: _Optional[_Union[datetime.timedelta, _duration_pb2.Duration, _Mapping]] = ..., max_failure_history: _Optional[int] = ..., invalid_offset_metadata_policy: _Optional[_Union[InvalidOffsetMetadataPolicy, str]] = ..., launch_token: _Optional[str] = ..., terminal_topic: _Optional[str] = ..., lease_duration: _Optional[_Union[datetime.timedelta, _duration_pb2.Duration, _Mapping]] = ..., heartbeat_interval: _Optional[_Union[datetime.timedelta, _duration_pb2.Duration, _Mapping]] = ..., reconnect_window: _Optional[_Union[datetime.timedelta, _duration_pb2.Duration, _Mapping]] = ..., message_buffer_size: _Optional[int] = ..., initial_load_factor: _Optional[int] = ..., maximum_load_factor: _Optional[int] = ..., pc_instance_tag: _Optional[str] = ...) -> None: ...

class Configured(_message.Message):
    __slots__ = ("topics", "topic_pattern", "max_concurrency", "executor_count", "capabilities", "ordering", "commit_mode", "commit_interval", "default_message_retry_delay", "send_timeout", "offset_commit_timeout", "shutdown_timeout", "drain_timeout", "threshold_for_time_spend_in_queue_warning", "sasl_authentication_retry_timeout", "sasl_authentication_exception_retry_backoff", "max_failure_history", "invalid_offset_metadata_policy", "terminal_topic", "lease_duration", "heartbeat_interval", "reconnect_window", "message_buffer_size", "initial_load_factor", "maximum_load_factor", "pc_instance_tag")
    TOPICS_FIELD_NUMBER: _ClassVar[int]
    TOPIC_PATTERN_FIELD_NUMBER: _ClassVar[int]
    MAX_CONCURRENCY_FIELD_NUMBER: _ClassVar[int]
    EXECUTOR_COUNT_FIELD_NUMBER: _ClassVar[int]
    CAPABILITIES_FIELD_NUMBER: _ClassVar[int]
    ORDERING_FIELD_NUMBER: _ClassVar[int]
    COMMIT_MODE_FIELD_NUMBER: _ClassVar[int]
    COMMIT_INTERVAL_FIELD_NUMBER: _ClassVar[int]
    DEFAULT_MESSAGE_RETRY_DELAY_FIELD_NUMBER: _ClassVar[int]
    SEND_TIMEOUT_FIELD_NUMBER: _ClassVar[int]
    OFFSET_COMMIT_TIMEOUT_FIELD_NUMBER: _ClassVar[int]
    SHUTDOWN_TIMEOUT_FIELD_NUMBER: _ClassVar[int]
    DRAIN_TIMEOUT_FIELD_NUMBER: _ClassVar[int]
    THRESHOLD_FOR_TIME_SPEND_IN_QUEUE_WARNING_FIELD_NUMBER: _ClassVar[int]
    SASL_AUTHENTICATION_RETRY_TIMEOUT_FIELD_NUMBER: _ClassVar[int]
    SASL_AUTHENTICATION_EXCEPTION_RETRY_BACKOFF_FIELD_NUMBER: _ClassVar[int]
    MAX_FAILURE_HISTORY_FIELD_NUMBER: _ClassVar[int]
    INVALID_OFFSET_METADATA_POLICY_FIELD_NUMBER: _ClassVar[int]
    TERMINAL_TOPIC_FIELD_NUMBER: _ClassVar[int]
    LEASE_DURATION_FIELD_NUMBER: _ClassVar[int]
    HEARTBEAT_INTERVAL_FIELD_NUMBER: _ClassVar[int]
    RECONNECT_WINDOW_FIELD_NUMBER: _ClassVar[int]
    MESSAGE_BUFFER_SIZE_FIELD_NUMBER: _ClassVar[int]
    INITIAL_LOAD_FACTOR_FIELD_NUMBER: _ClassVar[int]
    MAXIMUM_LOAD_FACTOR_FIELD_NUMBER: _ClassVar[int]
    PC_INSTANCE_TAG_FIELD_NUMBER: _ClassVar[int]
    topics: _containers.RepeatedScalarFieldContainer[str]
    topic_pattern: str
    max_concurrency: int
    executor_count: int
    capabilities: _containers.RepeatedScalarFieldContainer[str]
    ordering: ProcessingOrder
    commit_mode: CommitMode
    commit_interval: _duration_pb2.Duration
    default_message_retry_delay: _duration_pb2.Duration
    send_timeout: _duration_pb2.Duration
    offset_commit_timeout: _duration_pb2.Duration
    shutdown_timeout: _duration_pb2.Duration
    drain_timeout: _duration_pb2.Duration
    threshold_for_time_spend_in_queue_warning: _duration_pb2.Duration
    sasl_authentication_retry_timeout: _duration_pb2.Duration
    sasl_authentication_exception_retry_backoff: _duration_pb2.Duration
    max_failure_history: int
    invalid_offset_metadata_policy: InvalidOffsetMetadataPolicy
    terminal_topic: str
    lease_duration: _duration_pb2.Duration
    heartbeat_interval: _duration_pb2.Duration
    reconnect_window: _duration_pb2.Duration
    message_buffer_size: int
    initial_load_factor: int
    maximum_load_factor: int
    pc_instance_tag: str
    def __init__(self, topics: _Optional[_Iterable[str]] = ..., topic_pattern: _Optional[str] = ..., max_concurrency: _Optional[int] = ..., executor_count: _Optional[int] = ..., capabilities: _Optional[_Iterable[str]] = ..., ordering: _Optional[_Union[ProcessingOrder, str]] = ..., commit_mode: _Optional[_Union[CommitMode, str]] = ..., commit_interval: _Optional[_Union[datetime.timedelta, _duration_pb2.Duration, _Mapping]] = ..., default_message_retry_delay: _Optional[_Union[datetime.timedelta, _duration_pb2.Duration, _Mapping]] = ..., send_timeout: _Optional[_Union[datetime.timedelta, _duration_pb2.Duration, _Mapping]] = ..., offset_commit_timeout: _Optional[_Union[datetime.timedelta, _duration_pb2.Duration, _Mapping]] = ..., shutdown_timeout: _Optional[_Union[datetime.timedelta, _duration_pb2.Duration, _Mapping]] = ..., drain_timeout: _Optional[_Union[datetime.timedelta, _duration_pb2.Duration, _Mapping]] = ..., threshold_for_time_spend_in_queue_warning: _Optional[_Union[datetime.timedelta, _duration_pb2.Duration, _Mapping]] = ..., sasl_authentication_retry_timeout: _Optional[_Union[datetime.timedelta, _duration_pb2.Duration, _Mapping]] = ..., sasl_authentication_exception_retry_backoff: _Optional[_Union[datetime.timedelta, _duration_pb2.Duration, _Mapping]] = ..., max_failure_history: _Optional[int] = ..., invalid_offset_metadata_policy: _Optional[_Union[InvalidOffsetMetadataPolicy, str]] = ..., terminal_topic: _Optional[str] = ..., lease_duration: _Optional[_Union[datetime.timedelta, _duration_pb2.Duration, _Mapping]] = ..., heartbeat_interval: _Optional[_Union[datetime.timedelta, _duration_pb2.Duration, _Mapping]] = ..., reconnect_window: _Optional[_Union[datetime.timedelta, _duration_pb2.Duration, _Mapping]] = ..., message_buffer_size: _Optional[int] = ..., initial_load_factor: _Optional[int] = ..., maximum_load_factor: _Optional[int] = ..., pc_instance_tag: _Optional[str] = ...) -> None: ...

class Token(_message.Message):
    __slots__ = ("record_id", "epoch")
    RECORD_ID_FIELD_NUMBER: _ClassVar[int]
    EPOCH_FIELD_NUMBER: _ClassVar[int]
    record_id: str
    epoch: int
    def __init__(self, record_id: _Optional[str] = ..., epoch: _Optional[int] = ...) -> None: ...

class Record(_message.Message):
    __slots__ = ("topic", "partition", "offset", "key", "value")
    TOPIC_FIELD_NUMBER: _ClassVar[int]
    PARTITION_FIELD_NUMBER: _ClassVar[int]
    OFFSET_FIELD_NUMBER: _ClassVar[int]
    KEY_FIELD_NUMBER: _ClassVar[int]
    VALUE_FIELD_NUMBER: _ClassVar[int]
    topic: str
    partition: int
    offset: int
    key: bytes
    value: bytes
    def __init__(self, topic: _Optional[str] = ..., partition: _Optional[int] = ..., offset: _Optional[int] = ..., key: _Optional[bytes] = ..., value: _Optional[bytes] = ...) -> None: ...

class Dispatch(_message.Message):
    __slots__ = ("records",)
    RECORDS_FIELD_NUMBER: _ClassVar[int]
    records: _containers.RepeatedCompositeFieldContainer[DispatchRecord]
    def __init__(self, records: _Optional[_Iterable[_Union[DispatchRecord, _Mapping]]] = ...) -> None: ...

class DispatchRecord(_message.Message):
    __slots__ = ("token", "record", "attempt", "last_failure_at", "last_failure_reason")
    TOKEN_FIELD_NUMBER: _ClassVar[int]
    RECORD_FIELD_NUMBER: _ClassVar[int]
    ATTEMPT_FIELD_NUMBER: _ClassVar[int]
    LAST_FAILURE_AT_FIELD_NUMBER: _ClassVar[int]
    LAST_FAILURE_REASON_FIELD_NUMBER: _ClassVar[int]
    token: Token
    record: Record
    attempt: int
    last_failure_at: _timestamp_pb2.Timestamp
    last_failure_reason: str
    def __init__(self, token: _Optional[_Union[Token, _Mapping]] = ..., record: _Optional[_Union[Record, _Mapping]] = ..., attempt: _Optional[int] = ..., last_failure_at: _Optional[_Union[datetime.datetime, _timestamp_pb2.Timestamp, _Mapping]] = ..., last_failure_reason: _Optional[str] = ...) -> None: ...

class Report(_message.Message):
    __slots__ = ("token", "success", "failure", "terminal", "released")
    class Success(_message.Message):
        __slots__ = ("produce",)
        PRODUCE_FIELD_NUMBER: _ClassVar[int]
        produce: _containers.RepeatedCompositeFieldContainer[ProduceRecord]
        def __init__(self, produce: _Optional[_Iterable[_Union[ProduceRecord, _Mapping]]] = ...) -> None: ...
    class Failure(_message.Message):
        __slots__ = ("reason",)
        REASON_FIELD_NUMBER: _ClassVar[int]
        reason: str
        def __init__(self, reason: _Optional[str] = ...) -> None: ...
    class Terminal(_message.Message):
        __slots__ = ("reason",)
        REASON_FIELD_NUMBER: _ClassVar[int]
        reason: str
        def __init__(self, reason: _Optional[str] = ...) -> None: ...
    class Released(_message.Message):
        __slots__ = ()
        def __init__(self) -> None: ...
    TOKEN_FIELD_NUMBER: _ClassVar[int]
    SUCCESS_FIELD_NUMBER: _ClassVar[int]
    FAILURE_FIELD_NUMBER: _ClassVar[int]
    TERMINAL_FIELD_NUMBER: _ClassVar[int]
    RELEASED_FIELD_NUMBER: _ClassVar[int]
    token: Token
    success: Report.Success
    failure: Report.Failure
    terminal: Report.Terminal
    released: Report.Released
    def __init__(self, token: _Optional[_Union[Token, _Mapping]] = ..., success: _Optional[_Union[Report.Success, _Mapping]] = ..., failure: _Optional[_Union[Report.Failure, _Mapping]] = ..., terminal: _Optional[_Union[Report.Terminal, _Mapping]] = ..., released: _Optional[_Union[Report.Released, _Mapping]] = ...) -> None: ...

class ProduceRecord(_message.Message):
    __slots__ = ("topic", "key", "value")
    TOPIC_FIELD_NUMBER: _ClassVar[int]
    KEY_FIELD_NUMBER: _ClassVar[int]
    VALUE_FIELD_NUMBER: _ClassVar[int]
    topic: str
    key: bytes
    value: bytes
    def __init__(self, topic: _Optional[str] = ..., key: _Optional[bytes] = ..., value: _Optional[bytes] = ...) -> None: ...

class Heartbeat(_message.Message):
    __slots__ = ()
    def __init__(self) -> None: ...

class Manifest(_message.Message):
    __slots__ = ("tokens",)
    TOKENS_FIELD_NUMBER: _ClassVar[int]
    tokens: _containers.RepeatedCompositeFieldContainer[Token]
    def __init__(self, tokens: _Optional[_Iterable[_Union[Token, _Mapping]]] = ...) -> None: ...

class WorkerDied(_message.Message):
    __slots__ = ("tokens",)
    TOKENS_FIELD_NUMBER: _ClassVar[int]
    tokens: _containers.RepeatedCompositeFieldContainer[Token]
    def __init__(self, tokens: _Optional[_Iterable[_Union[Token, _Mapping]]] = ...) -> None: ...

class Drop(_message.Message):
    __slots__ = ("token",)
    TOKEN_FIELD_NUMBER: _ClassVar[int]
    token: Token
    def __init__(self, token: _Optional[_Union[Token, _Mapping]] = ...) -> None: ...

class Shutdown(_message.Message):
    __slots__ = ()
    def __init__(self) -> None: ...

class SetExecutorCount(_message.Message):
    __slots__ = ("executor_count",)
    EXECUTOR_COUNT_FIELD_NUMBER: _ClassVar[int]
    executor_count: int
    def __init__(self, executor_count: _Optional[int] = ...) -> None: ...
