# Generated by tools/generate_proto.py from the frozen proxy.proto - do not edit.
# Regenerate with `make proto`; `make proto-check` fails when this copy has drifted.
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import proxy_pb2 as proxy__pb2

GRPC_GENERATED_VERSION = '1.73.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in proxy_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ProxyServiceStub(object):
    """The single bidirectional session stream between a client library's admin
    connection and the sidecar proxy. The first client message must be
    Configure (fresh session) or Manifest (reconnect within the protection
    window); the proxy replies Configured either way, and then dispatches
    records.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Session = channel.stream_stream(
                '/parallelconsumer.proxy.v1.ProxyService/Session',
                request_serializer=proxy__pb2.ClientMessage.SerializeToString,
                response_deserializer=proxy__pb2.ProxyMessage.FromString,
                _registered_method=True)


class ProxyServiceServicer(object):
    """The single bidirectional session stream between a client library's admin
    connection and the sidecar proxy. The first client message must be
    Configure (fresh session) or Manifest (reconnect within the protection
    window); the proxy replies Configured either way, and then dispatches
    records.
    """

    def Session(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProxyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Session': grpc.stream_stream_rpc_method_handler(
                    servicer.Session,
                    request_deserializer=proxy__pb2.ClientMessage.FromString,
                    response_serializer=proxy__pb2.ProxyMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'parallelconsumer.proxy.v1.ProxyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('parallelconsumer.proxy.v1.ProxyService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProxyService(object):
    """The single bidirectional session stream between a client library's admin
    connection and the sidecar proxy. The first client message must be
    Configure (fresh session) or Manifest (reconnect within the protection
    window); the proxy replies Configured either way, and then dispatches
    records.
    """

    @staticmethod
    def Session(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/parallelconsumer.proxy.v1.ProxyService/Session',
            proxy__pb2.ClientMessage.SerializeToString,
            proxy__pb2.ProxyMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
