# Generated by tools/generate_proto.py from parallel-consumer-proxy-streams/src/main/proto/parallelconsumer/streams/v1alpha1/streams.proto - do not edit.
# Regenerate with `make proto`; `make proto-check` fails when this copy has drifted.
from google.protobuf.internal import containers as _containers
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from collections.abc import Mapping as _Mapping
from typing import ClassVar as _ClassVar, Optional as _Optional, Union as _Union

DESCRIPTOR: _descriptor.FileDescriptor

class StreamsClientMessage(_message.Message):
    __slots__ = ("open", "builder_call", "register_function", "describe_complete", "invocation_result")
    OPEN_FIELD_NUMBER: _ClassVar[int]
    BUILDER_CALL_FIELD_NUMBER: _ClassVar[int]
    REGISTER_FUNCTION_FIELD_NUMBER: _ClassVar[int]
    DESCRIBE_COMPLETE_FIELD_NUMBER: _ClassVar[int]
    INVOCATION_RESULT_FIELD_NUMBER: _ClassVar[int]
    open: Open
    builder_call: BuilderCall
    register_function: RegisterFunction
    describe_complete: DescribeComplete
    invocation_result: InvocationResult
    def __init__(self, open: _Optional[_Union[Open, _Mapping]] = ..., builder_call: _Optional[_Union[BuilderCall, _Mapping]] = ..., register_function: _Optional[_Union[RegisterFunction, _Mapping]] = ..., describe_complete: _Optional[_Union[DescribeComplete, _Mapping]] = ..., invocation_result: _Optional[_Union[InvocationResult, _Mapping]] = ...) -> None: ...

class StreamsServerMessage(_message.Message):
    __slots__ = ("ready", "handle_assigned", "invocation", "fault")
    READY_FIELD_NUMBER: _ClassVar[int]
    HANDLE_ASSIGNED_FIELD_NUMBER: _ClassVar[int]
    INVOCATION_FIELD_NUMBER: _ClassVar[int]
    FAULT_FIELD_NUMBER: _ClassVar[int]
    ready: Ready
    handle_assigned: HandleAssigned
    invocation: Invocation
    fault: Fault
    def __init__(self, ready: _Optional[_Union[Ready, _Mapping]] = ..., handle_assigned: _Optional[_Union[HandleAssigned, _Mapping]] = ..., invocation: _Optional[_Union[Invocation, _Mapping]] = ..., fault: _Optional[_Union[Fault, _Mapping]] = ...) -> None: ...

class Open(_message.Message):
    __slots__ = ("application_id", "kafka_properties")
    class KafkaPropertiesEntry(_message.Message):
        __slots__ = ("key", "value")
        KEY_FIELD_NUMBER: _ClassVar[int]
        VALUE_FIELD_NUMBER: _ClassVar[int]
        key: str
        value: str
        def __init__(self, key: _Optional[str] = ..., value: _Optional[str] = ...) -> None: ...
    APPLICATION_ID_FIELD_NUMBER: _ClassVar[int]
    KAFKA_PROPERTIES_FIELD_NUMBER: _ClassVar[int]
    application_id: str
    kafka_properties: _containers.ScalarMap[str, str]
    def __init__(self, application_id: _Optional[str] = ..., kafka_properties: _Optional[_Mapping[str, str]] = ...) -> None: ...

class Ready(_message.Message):
    __slots__ = ("application_id",)
    APPLICATION_ID_FIELD_NUMBER: _ClassVar[int]
    application_id: str
    def __init__(self, application_id: _Optional[str] = ...) -> None: ...

class BuilderCall(_message.Message):
    __slots__ = ("call_id", "source", "map_values", "group_by_key", "count", "sink")
    CALL_ID_FIELD_NUMBER: _ClassVar[int]
    SOURCE_FIELD_NUMBER: _ClassVar[int]
    MAP_VALUES_FIELD_NUMBER: _ClassVar[int]
    GROUP_BY_KEY_FIELD_NUMBER: _ClassVar[int]
    COUNT_FIELD_NUMBER: _ClassVar[int]
    SINK_FIELD_NUMBER: _ClassVar[int]
    call_id: int
    source: Source
    map_values: MapValues
    group_by_key: GroupByKey
    count: Count
    sink: Sink
    def __init__(self, call_id: _Optional[int] = ..., source: _Optional[_Union[Source, _Mapping]] = ..., map_values: _Optional[_Union[MapValues, _Mapping]] = ..., group_by_key: _Optional[_Union[GroupByKey, _Mapping]] = ..., count: _Optional[_Union[Count, _Mapping]] = ..., sink: _Optional[_Union[Sink, _Mapping]] = ...) -> None: ...

class Source(_message.Message):
    __slots__ = ("topic",)
    TOPIC_FIELD_NUMBER: _ClassVar[int]
    topic: str
    def __init__(self, topic: _Optional[str] = ...) -> None: ...

class MapValues(_message.Message):
    __slots__ = ("handle", "function_token")
    HANDLE_FIELD_NUMBER: _ClassVar[int]
    FUNCTION_TOKEN_FIELD_NUMBER: _ClassVar[int]
    handle: int
    function_token: int
    def __init__(self, handle: _Optional[int] = ..., function_token: _Optional[int] = ...) -> None: ...

class GroupByKey(_message.Message):
    __slots__ = ("handle",)
    HANDLE_FIELD_NUMBER: _ClassVar[int]
    handle: int
    def __init__(self, handle: _Optional[int] = ...) -> None: ...

class Count(_message.Message):
    __slots__ = ("handle", "store_name")
    HANDLE_FIELD_NUMBER: _ClassVar[int]
    STORE_NAME_FIELD_NUMBER: _ClassVar[int]
    handle: int
    store_name: str
    def __init__(self, handle: _Optional[int] = ..., store_name: _Optional[str] = ...) -> None: ...

class Sink(_message.Message):
    __slots__ = ("handle", "topic")
    HANDLE_FIELD_NUMBER: _ClassVar[int]
    TOPIC_FIELD_NUMBER: _ClassVar[int]
    handle: int
    topic: str
    def __init__(self, handle: _Optional[int] = ..., topic: _Optional[str] = ...) -> None: ...

class HandleAssigned(_message.Message):
    __slots__ = ("call_id", "handle")
    CALL_ID_FIELD_NUMBER: _ClassVar[int]
    HANDLE_FIELD_NUMBER: _ClassVar[int]
    call_id: int
    handle: int
    def __init__(self, call_id: _Optional[int] = ..., handle: _Optional[int] = ...) -> None: ...

class RegisterFunction(_message.Message):
    __slots__ = ("token", "description")
    TOKEN_FIELD_NUMBER: _ClassVar[int]
    DESCRIPTION_FIELD_NUMBER: _ClassVar[int]
    token: int
    description: str
    def __init__(self, token: _Optional[int] = ..., description: _Optional[str] = ...) -> None: ...

class DescribeComplete(_message.Message):
    __slots__ = ()
    def __init__(self) -> None: ...

class Invocation(_message.Message):
    __slots__ = ("correlation", "function_token", "key", "value")
    CORRELATION_FIELD_NUMBER: _ClassVar[int]
    FUNCTION_TOKEN_FIELD_NUMBER: _ClassVar[int]
    KEY_FIELD_NUMBER: _ClassVar[int]
    VALUE_FIELD_NUMBER: _ClassVar[int]
    correlation: int
    function_token: int
    key: bytes
    value: bytes
    def __init__(self, correlation: _Optional[int] = ..., function_token: _Optional[int] = ..., key: _Optional[bytes] = ..., value: _Optional[bytes] = ...) -> None: ...

class InvocationResult(_message.Message):
    __slots__ = ("correlation", "value", "error")
    CORRELATION_FIELD_NUMBER: _ClassVar[int]
    VALUE_FIELD_NUMBER: _ClassVar[int]
    ERROR_FIELD_NUMBER: _ClassVar[int]
    correlation: int
    value: bytes
    error: str
    def __init__(self, correlation: _Optional[int] = ..., value: _Optional[bytes] = ..., error: _Optional[str] = ...) -> None: ...

class Fault(_message.Message):
    __slots__ = ("reason",)
    REASON_FIELD_NUMBER: _ClassVar[int]
    reason: str
    def __init__(self, reason: _Optional[str] = ...) -> None: ...
