# Generated by tools/generate_proto.py from parallel-consumer-proxy-streams/src/main/proto/parallelconsumer/streams/v1alpha1/streams.proto - do not edit.
# Regenerate with `make proto`; `make proto-check` fails when this copy has drifted.
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import streams_pb2 as streams__pb2

GRPC_GENERATED_VERSION = '1.73.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in streams_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StreamsServiceStub(object):
    """One bidirectional stream carries a whole session: the handshake, the topology description, and
    then per-record invocations for as long as the topology runs.

    It does NOT reuse the v1 Session RPC, and that is forced rather than stylistic. The v1 handshake
    rejects a Configure naming neither a topic list nor a topic pattern, and builds a Parallel
    Consumer engine from that subscription. A Streams topology names its own sources, so a Streams
    session cannot open on it without fabricating a subscription and standing up an engine nothing
    uses.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Session = channel.stream_stream(
                '/parallelconsumer.streams.v1alpha1.StreamsService/Session',
                request_serializer=streams__pb2.StreamsClientMessage.SerializeToString,
                response_deserializer=streams__pb2.StreamsServerMessage.FromString,
                _registered_method=True)


class StreamsServiceServicer(object):
    """One bidirectional stream carries a whole session: the handshake, the topology description, and
    then per-record invocations for as long as the topology runs.

    It does NOT reuse the v1 Session RPC, and that is forced rather than stylistic. The v1 handshake
    rejects a Configure naming neither a topic list nor a topic pattern, and builds a Parallel
    Consumer engine from that subscription. A Streams topology names its own sources, so a Streams
    session cannot open on it without fabricating a subscription and standing up an engine nothing
    uses.
    """

    def Session(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StreamsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Session': grpc.stream_stream_rpc_method_handler(
                    servicer.Session,
                    request_deserializer=streams__pb2.StreamsClientMessage.FromString,
                    response_serializer=streams__pb2.StreamsServerMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'parallelconsumer.streams.v1alpha1.StreamsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('parallelconsumer.streams.v1alpha1.StreamsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StreamsService(object):
    """One bidirectional stream carries a whole session: the handshake, the topology description, and
    then per-record invocations for as long as the topology runs.

    It does NOT reuse the v1 Session RPC, and that is forced rather than stylistic. The v1 handshake
    rejects a Configure naming neither a topic list nor a topic pattern, and builds a Parallel
    Consumer engine from that subscription. A Streams topology names its own sources, so a Streams
    session cannot open on it without fabricating a subscription and standing up an engine nothing
    uses.
    """

    @staticmethod
    def Session(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/parallelconsumer.streams.v1alpha1.StreamsService/Session',
            streams__pb2.StreamsClientMessage.SerializeToString,
            streams__pb2.StreamsServerMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
