# Generated by tools/generate_proto.py from parallel-consumer-proxy-streams/src/main/proto/parallelconsumer/streams/v1alpha1/streams.proto - do not edit.
# Regenerate with `make proto`; `make proto-check` fails when this copy has drifted.
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from collections.abc import Iterable as _Iterable, Mapping as _Mapping
from typing import ClassVar as _ClassVar, Optional as _Optional, Union as _Union

DESCRIPTOR: _descriptor.FileDescriptor

class HandleKind(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    HANDLE_KIND_UNSPECIFIED: _ClassVar[HandleKind]
    HANDLE_KIND_STREAM: _ClassVar[HandleKind]
    HANDLE_KIND_GROUPED_STREAM: _ClassVar[HandleKind]
    HANDLE_KIND_TABLE: _ClassVar[HandleKind]

class DataType(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    DATA_TYPE_UNSPECIFIED: _ClassVar[DataType]
    DATA_TYPE_BYTES: _ClassVar[DataType]
    DATA_TYPE_LONG: _ClassVar[DataType]

class NodeKind(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    NODE_KIND_UNSPECIFIED: _ClassVar[NodeKind]
    NODE_KIND_SOURCE: _ClassVar[NodeKind]
    NODE_KIND_PROCESSOR: _ClassVar[NodeKind]
    NODE_KIND_SINK: _ClassVar[NodeKind]
HANDLE_KIND_UNSPECIFIED: HandleKind
HANDLE_KIND_STREAM: HandleKind
HANDLE_KIND_GROUPED_STREAM: HandleKind
HANDLE_KIND_TABLE: HandleKind
DATA_TYPE_UNSPECIFIED: DataType
DATA_TYPE_BYTES: DataType
DATA_TYPE_LONG: DataType
NODE_KIND_UNSPECIFIED: NodeKind
NODE_KIND_SOURCE: NodeKind
NODE_KIND_PROCESSOR: NodeKind
NODE_KIND_SINK: NodeKind

class StreamsClientMessage(_message.Message):
    __slots__ = ("open", "builder_call", "register_function", "describe_complete", "invocation_result", "describe", "get")
    OPEN_FIELD_NUMBER: _ClassVar[int]
    BUILDER_CALL_FIELD_NUMBER: _ClassVar[int]
    REGISTER_FUNCTION_FIELD_NUMBER: _ClassVar[int]
    DESCRIBE_COMPLETE_FIELD_NUMBER: _ClassVar[int]
    INVOCATION_RESULT_FIELD_NUMBER: _ClassVar[int]
    DESCRIBE_FIELD_NUMBER: _ClassVar[int]
    GET_FIELD_NUMBER: _ClassVar[int]
    open: Open
    builder_call: BuilderCall
    register_function: RegisterFunction
    describe_complete: DescribeComplete
    invocation_result: InvocationResult
    describe: Describe
    get: Get
    def __init__(self, open: _Optional[_Union[Open, _Mapping]] = ..., builder_call: _Optional[_Union[BuilderCall, _Mapping]] = ..., register_function: _Optional[_Union[RegisterFunction, _Mapping]] = ..., describe_complete: _Optional[_Union[DescribeComplete, _Mapping]] = ..., invocation_result: _Optional[_Union[InvocationResult, _Mapping]] = ..., describe: _Optional[_Union[Describe, _Mapping]] = ..., get: _Optional[_Union[Get, _Mapping]] = ...) -> None: ...

class StreamsServerMessage(_message.Message):
    __slots__ = ("ready", "handle_assigned", "invocation", "fault", "topology_description", "get_result")
    READY_FIELD_NUMBER: _ClassVar[int]
    HANDLE_ASSIGNED_FIELD_NUMBER: _ClassVar[int]
    INVOCATION_FIELD_NUMBER: _ClassVar[int]
    FAULT_FIELD_NUMBER: _ClassVar[int]
    TOPOLOGY_DESCRIPTION_FIELD_NUMBER: _ClassVar[int]
    GET_RESULT_FIELD_NUMBER: _ClassVar[int]
    ready: Ready
    handle_assigned: HandleAssigned
    invocation: Invocation
    fault: Fault
    topology_description: TopologyDescription
    get_result: GetResult
    def __init__(self, ready: _Optional[_Union[Ready, _Mapping]] = ..., handle_assigned: _Optional[_Union[HandleAssigned, _Mapping]] = ..., invocation: _Optional[_Union[Invocation, _Mapping]] = ..., fault: _Optional[_Union[Fault, _Mapping]] = ..., topology_description: _Optional[_Union[TopologyDescription, _Mapping]] = ..., get_result: _Optional[_Union[GetResult, _Mapping]] = ...) -> None: ...

class Open(_message.Message):
    __slots__ = ("application_id", "kafka_properties")
    class KafkaPropertiesEntry(_message.Message):
        __slots__ = ("key", "value")
        KEY_FIELD_NUMBER: _ClassVar[int]
        VALUE_FIELD_NUMBER: _ClassVar[int]
        key: str
        value: str
        def __init__(self, key: _Optional[str] = ..., value: _Optional[str] = ...) -> None: ...
    APPLICATION_ID_FIELD_NUMBER: _ClassVar[int]
    KAFKA_PROPERTIES_FIELD_NUMBER: _ClassVar[int]
    application_id: str
    kafka_properties: _containers.ScalarMap[str, str]
    def __init__(self, application_id: _Optional[str] = ..., kafka_properties: _Optional[_Mapping[str, str]] = ...) -> None: ...

class Ready(_message.Message):
    __slots__ = ("application_id",)
    APPLICATION_ID_FIELD_NUMBER: _ClassVar[int]
    application_id: str
    def __init__(self, application_id: _Optional[str] = ...) -> None: ...

class BuilderCall(_message.Message):
    __slots__ = ("call_id", "source", "map_values", "group_by_key", "count", "sink", "reduce")
    CALL_ID_FIELD_NUMBER: _ClassVar[int]
    SOURCE_FIELD_NUMBER: _ClassVar[int]
    MAP_VALUES_FIELD_NUMBER: _ClassVar[int]
    GROUP_BY_KEY_FIELD_NUMBER: _ClassVar[int]
    COUNT_FIELD_NUMBER: _ClassVar[int]
    SINK_FIELD_NUMBER: _ClassVar[int]
    REDUCE_FIELD_NUMBER: _ClassVar[int]
    call_id: int
    source: Source
    map_values: MapValues
    group_by_key: GroupByKey
    count: Count
    sink: Sink
    reduce: Reduce
    def __init__(self, call_id: _Optional[int] = ..., source: _Optional[_Union[Source, _Mapping]] = ..., map_values: _Optional[_Union[MapValues, _Mapping]] = ..., group_by_key: _Optional[_Union[GroupByKey, _Mapping]] = ..., count: _Optional[_Union[Count, _Mapping]] = ..., sink: _Optional[_Union[Sink, _Mapping]] = ..., reduce: _Optional[_Union[Reduce, _Mapping]] = ...) -> None: ...

class Source(_message.Message):
    __slots__ = ("topic",)
    TOPIC_FIELD_NUMBER: _ClassVar[int]
    topic: str
    def __init__(self, topic: _Optional[str] = ...) -> None: ...

class MapValues(_message.Message):
    __slots__ = ("handle", "function_token")
    HANDLE_FIELD_NUMBER: _ClassVar[int]
    FUNCTION_TOKEN_FIELD_NUMBER: _ClassVar[int]
    handle: int
    function_token: int
    def __init__(self, handle: _Optional[int] = ..., function_token: _Optional[int] = ...) -> None: ...

class GroupByKey(_message.Message):
    __slots__ = ("handle",)
    HANDLE_FIELD_NUMBER: _ClassVar[int]
    handle: int
    def __init__(self, handle: _Optional[int] = ...) -> None: ...

class Count(_message.Message):
    __slots__ = ("handle", "store_name")
    HANDLE_FIELD_NUMBER: _ClassVar[int]
    STORE_NAME_FIELD_NUMBER: _ClassVar[int]
    handle: int
    store_name: str
    def __init__(self, handle: _Optional[int] = ..., store_name: _Optional[str] = ...) -> None: ...

class Reduce(_message.Message):
    __slots__ = ("handle", "function_token", "store_name")
    HANDLE_FIELD_NUMBER: _ClassVar[int]
    FUNCTION_TOKEN_FIELD_NUMBER: _ClassVar[int]
    STORE_NAME_FIELD_NUMBER: _ClassVar[int]
    handle: int
    function_token: int
    store_name: str
    def __init__(self, handle: _Optional[int] = ..., function_token: _Optional[int] = ..., store_name: _Optional[str] = ...) -> None: ...

class Sink(_message.Message):
    __slots__ = ("handle", "topic")
    HANDLE_FIELD_NUMBER: _ClassVar[int]
    TOPIC_FIELD_NUMBER: _ClassVar[int]
    handle: int
    topic: str
    def __init__(self, handle: _Optional[int] = ..., topic: _Optional[str] = ...) -> None: ...

class HandleAssigned(_message.Message):
    __slots__ = ("call_id", "handle", "type")
    CALL_ID_FIELD_NUMBER: _ClassVar[int]
    HANDLE_FIELD_NUMBER: _ClassVar[int]
    TYPE_FIELD_NUMBER: _ClassVar[int]
    call_id: int
    handle: int
    type: HandleType
    def __init__(self, call_id: _Optional[int] = ..., handle: _Optional[int] = ..., type: _Optional[_Union[HandleType, _Mapping]] = ...) -> None: ...

class HandleType(_message.Message):
    __slots__ = ("kind", "key_type", "value_type")
    KIND_FIELD_NUMBER: _ClassVar[int]
    KEY_TYPE_FIELD_NUMBER: _ClassVar[int]
    VALUE_TYPE_FIELD_NUMBER: _ClassVar[int]
    kind: HandleKind
    key_type: DataType
    value_type: DataType
    def __init__(self, kind: _Optional[_Union[HandleKind, str]] = ..., key_type: _Optional[_Union[DataType, str]] = ..., value_type: _Optional[_Union[DataType, str]] = ...) -> None: ...

class RegisterFunction(_message.Message):
    __slots__ = ("token", "description")
    TOKEN_FIELD_NUMBER: _ClassVar[int]
    DESCRIPTION_FIELD_NUMBER: _ClassVar[int]
    token: int
    description: str
    def __init__(self, token: _Optional[int] = ..., description: _Optional[str] = ...) -> None: ...

class DescribeComplete(_message.Message):
    __slots__ = ()
    def __init__(self) -> None: ...

class Get(_message.Message):
    __slots__ = ("store_name", "key")
    STORE_NAME_FIELD_NUMBER: _ClassVar[int]
    KEY_FIELD_NUMBER: _ClassVar[int]
    store_name: str
    key: bytes
    def __init__(self, store_name: _Optional[str] = ..., key: _Optional[bytes] = ...) -> None: ...

class GetResult(_message.Message):
    __slots__ = ("found", "value", "value_type", "error")
    FOUND_FIELD_NUMBER: _ClassVar[int]
    VALUE_FIELD_NUMBER: _ClassVar[int]
    VALUE_TYPE_FIELD_NUMBER: _ClassVar[int]
    ERROR_FIELD_NUMBER: _ClassVar[int]
    found: bool
    value: bytes
    value_type: DataType
    error: str
    def __init__(self, found: bool = ..., value: _Optional[bytes] = ..., value_type: _Optional[_Union[DataType, str]] = ..., error: _Optional[str] = ...) -> None: ...

class Describe(_message.Message):
    __slots__ = ()
    def __init__(self) -> None: ...

class TopologyDescription(_message.Message):
    __slots__ = ("text", "subtopologies", "global_store_names")
    TEXT_FIELD_NUMBER: _ClassVar[int]
    SUBTOPOLOGIES_FIELD_NUMBER: _ClassVar[int]
    GLOBAL_STORE_NAMES_FIELD_NUMBER: _ClassVar[int]
    text: str
    subtopologies: _containers.RepeatedCompositeFieldContainer[Subtopology]
    global_store_names: _containers.RepeatedScalarFieldContainer[str]
    def __init__(self, text: _Optional[str] = ..., subtopologies: _Optional[_Iterable[_Union[Subtopology, _Mapping]]] = ..., global_store_names: _Optional[_Iterable[str]] = ...) -> None: ...

class Subtopology(_message.Message):
    __slots__ = ("id", "nodes")
    ID_FIELD_NUMBER: _ClassVar[int]
    NODES_FIELD_NUMBER: _ClassVar[int]
    id: int
    nodes: _containers.RepeatedCompositeFieldContainer[Node]
    def __init__(self, id: _Optional[int] = ..., nodes: _Optional[_Iterable[_Union[Node, _Mapping]]] = ...) -> None: ...

class Node(_message.Message):
    __slots__ = ("name", "predecessors", "successors", "kind", "topics", "stores", "topic_pattern")
    NAME_FIELD_NUMBER: _ClassVar[int]
    PREDECESSORS_FIELD_NUMBER: _ClassVar[int]
    SUCCESSORS_FIELD_NUMBER: _ClassVar[int]
    KIND_FIELD_NUMBER: _ClassVar[int]
    TOPICS_FIELD_NUMBER: _ClassVar[int]
    STORES_FIELD_NUMBER: _ClassVar[int]
    TOPIC_PATTERN_FIELD_NUMBER: _ClassVar[int]
    name: str
    predecessors: _containers.RepeatedScalarFieldContainer[str]
    successors: _containers.RepeatedScalarFieldContainer[str]
    kind: NodeKind
    topics: _containers.RepeatedScalarFieldContainer[str]
    stores: _containers.RepeatedScalarFieldContainer[str]
    topic_pattern: str
    def __init__(self, name: _Optional[str] = ..., predecessors: _Optional[_Iterable[str]] = ..., successors: _Optional[_Iterable[str]] = ..., kind: _Optional[_Union[NodeKind, str]] = ..., topics: _Optional[_Iterable[str]] = ..., stores: _Optional[_Iterable[str]] = ..., topic_pattern: _Optional[str] = ...) -> None: ...

class Invocation(_message.Message):
    __slots__ = ("correlation", "function_token", "key", "value", "aggregate")
    CORRELATION_FIELD_NUMBER: _ClassVar[int]
    FUNCTION_TOKEN_FIELD_NUMBER: _ClassVar[int]
    KEY_FIELD_NUMBER: _ClassVar[int]
    VALUE_FIELD_NUMBER: _ClassVar[int]
    AGGREGATE_FIELD_NUMBER: _ClassVar[int]
    correlation: int
    function_token: int
    key: bytes
    value: bytes
    aggregate: bytes
    def __init__(self, correlation: _Optional[int] = ..., function_token: _Optional[int] = ..., key: _Optional[bytes] = ..., value: _Optional[bytes] = ..., aggregate: _Optional[bytes] = ...) -> None: ...

class InvocationResult(_message.Message):
    __slots__ = ("correlation", "value", "error")
    CORRELATION_FIELD_NUMBER: _ClassVar[int]
    VALUE_FIELD_NUMBER: _ClassVar[int]
    ERROR_FIELD_NUMBER: _ClassVar[int]
    correlation: int
    value: bytes
    error: str
    def __init__(self, correlation: _Optional[int] = ..., value: _Optional[bytes] = ..., error: _Optional[str] = ...) -> None: ...

class Fault(_message.Message):
    __slots__ = ("reason",)
    REASON_FIELD_NUMBER: _ClassVar[int]
    reason: str
    def __init__(self, reason: _Optional[str] = ...) -> None: ...
