package io.confluent.parallelconsumer.streams.integrationTests;
/*-
 * Copyright (C) 2026 Antony Stubbs and contributors
 */

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

/**
 * A stock Kafka Streams baseline, read back from the tracked fixture file that generated it.
 * <p>
 * <b>These fixtures cannot be produced in this module, and that is the point.</b> This module compiles
 * patched copies of four {@code org.apache.kafka.streams.processor.internals} classes into its own build
 * output, which precedes the {@code kafka-streams} jar on the classpath, so every {@code KafkaStreams}
 * instance in this JVM runs the patch. A "stock arm" written here would share every defect the patch
 * introduced and the comparison would prove nothing. The fixtures come from
 * {@code parallel-consumer-example-streams}, which does not depend on this module and asserts its own
 * classpath is stock before recording a row.
 * <p>
 * The fixture carries the <b>inputs</b> as well as the outputs, and the tests here replay those inputs rather
 * than rebuilding them from a second copy of the generation rules - the two modules cannot share code in this
 * reactor order, so replaying is what stops the arms drifting apart in what they were fed.
 *
 * @author Antony Stubbs
 * @see PcDrivenStreamsProofTest
 * @see PcDrivenStatefulProofTest
 */
final class BaselineFixture {

    private String topology;
    private String probeHeader;
    private final List<Row> inputs = new ArrayList<>();
    private final List<Row> outputs = new ArrayList<>();

    private BaselineFixture() {
    }

    static BaselineFixture load(final String resource) throws IOException {
        BaselineFixture fixture = new BaselineFixture();
        try (InputStream in = BaselineFixture.class.getResourceAsStream(resource)) {
            if (in == null) {
                throw new IllegalStateException("Stock baseline fixture " + resource + " is not on the test "
                        + "classpath. Fixtures are generated by the Stock*BaselineFixtureTest classes in "
                        + "parallel-consumer-example-streams - see those classes for the command. This module "
                        + "cannot fabricate one locally: a baseline produced in this JVM would run the patched "
                        + "classes and would not be a baseline at all.");
            }
            BufferedReader reader = new BufferedReader(new InputStreamReader(in, StandardCharsets.UTF_8));
            String line;
            while ((line = reader.readLine()) != null) {
                if (line.isEmpty() || line.charAt(0) == '#') {
                    continue;
                }
                String[] parts = line.split("\t", -1);
                switch (parts[0]) {
                    case "fixtureVersion":
                        if (!"1".equals(parts[1])) {
                            throw new IllegalStateException("Unsupported fixture version " + parts[1]);
                        }
                        break;
                    case "topology":
                        fixture.topology = parts[1];
                        break;
                    case "probeHeader":
                        fixture.probeHeader = parts[1];
                        break;
                    case "in":
                        fixture.inputs.add(new Row(parts[1], parts[2], Long.parseLong(parts[3])));
                        break;
                    case "out":
                        fixture.outputs.add(new Row(parts[1], parts[2], Long.parseLong(parts[3])));
                        break;
                    default:
                        throw new IllegalStateException("Unrecognised fixture row type '" + parts[0] + "'");
                }
            }
        }
        if (fixture.topology == null || fixture.probeHeader == null) {
            throw new IllegalStateException("Fixture " + resource + " is missing its topology/probeHeader header rows");
        }
        return fixture;
    }

    String getTopology() {
        return topology;
    }

    String getProbeHeader() {
        return probeHeader;
    }

    List<Row> getInputs() {
        return inputs;
    }

    List<Row> getOutputs() {
        return outputs;
    }

    static Map<String, List<Row>> groupByKey(final List<Row> rows) {
        Map<String, List<Row>> byKey = new LinkedHashMap<>();
        for (Row row : rows) {
            byKey.computeIfAbsent(row.getKey(), k -> new ArrayList<>()).add(row);
        }
        return byKey;
    }

    /**
     * One emitted or expected record. Value equality is what makes the multiset comparison a multiset
     * comparison; the timestamp is in it because carrying the input record's timestamp to the sink is an
     * ambient read of the confined context, and dropping it from the comparison would drop the assertion.
     */
    static final class Row {
        private final String key;
        private final String value;
        private final long timestamp;

        Row(final String key, final String value, final long timestamp) {
            this.key = key;
            this.value = value;
            this.timestamp = timestamp;
        }

        String getKey() {
            return key;
        }

        String getValue() {
            return value;
        }

        long getTimestamp() {
            return timestamp;
        }

        @Override
        public boolean equals(final Object other) {
            if (this == other) {
                return true;
            }
            if (!(other instanceof Row)) {
                return false;
            }
            Row that = (Row) other;
            return timestamp == that.timestamp && key.equals(that.key) && value.equals(that.value);
        }

        @Override
        public int hashCode() {
            return Objects.hash(key, value, timestamp);
        }

        @Override
        public String toString() {
            return key + "=" + value + "@" + timestamp;
        }
    }
}
